import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Icon, LogoMark } from "../lib/icons";

type Screen = "splash" | "onboarding" | "login" | "home" | "browse" | "detail" | "sell" | "events" | "event" | "chat" | "profile" | "safety" | "notifications" | "saved" | "dashboard" | "empty" | "loading";

const products = [
  ["MacBook Pro 2019", "₦620,000", "/seed/dell-xps-13.jpg"],
  ["AirPods Pro (2nd Gen)", "₦185,000", "/seed/airpods-pro-2.jpg"],
  ["Google Pixel 7a", "₦235,000", "/seed/google-pixel-7a.jpg"],
  ["College textbooks", "₦18,500", "/seed/college-textbooks.jpg"],
  ["Nike Air Force 1", "₦72,000", "/seed/air-force-1.jpg"],
  ["JBL Flip 4 speaker", "₦48,000", "/seed/jbl-flip-4.jpg"],
] as const;
const people = ["Chioma A.", "David O.", "Tobi M.", "Aisha K."];

function AppBar({ title, back, onBack, action }: { title: string; back?: boolean; onBack?: () => void; action?: React.ReactNode }) { return <div className="proto-appbar">{back ? <button className="proto-icon-btn" onClick={onBack}><Icon name="arrowL" size={18} /></button> : <LogoMark size={27} />}<b>{title}</b><span className="proto-bar-spacer" />{action || <button className="proto-icon-btn"><Icon name="bell" size={18} /></button>}</div>; }
function BottomNav({ screen, go }: { screen: Screen; go: (s: Screen) => void }) { return <nav className="proto-bottom"><button className={screen === "home" ? "on" : ""} onClick={() => go("home")}><Icon name="store" size={19} /><span>Home</span></button><button className={screen === "browse" || screen === "detail" ? "on" : ""} onClick={() => go("browse")}><Icon name="grid" size={19} /><span>Browse</span></button><button className="sell-tab" onClick={() => go("sell")}><span><Icon name="plus" size={21} /></span><small>Sell</small></button><button className={screen === "events" || screen === "event" ? "on" : ""} onClick={() => go("events")}><Icon name="calendar" size={19} /><span>Events</span></button><button className={screen === "profile" || screen === "dashboard" ? "on" : ""} onClick={() => go("profile")}><Icon name="user" size={19} /><span>Profile</span></button></nav>; }
function SectionTitle({ title, action, onAction }: { title: string; action?: string; onAction?: () => void }) { return <div className="proto-section-title"><b>{title}</b>{action && <button onClick={onAction}>{action} <Icon name="arrowR" size={12} /></button>}</div>; }
function ProductCard({ p, onClick }: { p: typeof products[number]; onClick: () => void }) { return <button className="proto-product" onClick={onClick}><div className="proto-product-img"><img src={p[2]} alt="" /><span className="proto-heart"><Icon name="heart" size={14} /></span></div><div className="proto-product-copy"><small>VERIFIED SELLER</small><b>{p[0]}</b><strong>{p[1]}</strong><span><Icon name="location" size={11} /> UNILAG · 2h ago</span></div></button>; }

export default function Prototype() {
  const [screen, setScreen] = useState<Screen>("home");
  const [onboard, setOnboard] = useState(0);
  const [sellStep, setSellStep] = useState(0);
  const [liked, setLiked] = useState(false);
  const go = (s: Screen) => setScreen(s);
  const product = useMemo(() => products[0], []);
  const onboarding = [
    ["Welcome to OjaX", "Your campus, one trusted market.", "/brand-assets/ojax-student-seller.png"],
    ["Buy & Sell Safely", "Trade with verified students and meet in places you know.", "/brand-assets/ojax-marketplace-products.png"],
    ["Discover Campus Events", "Find the people, places and moments that make campus yours.", "/brand-assets/ojax-campus-event.png"],
    ["Verified Community", "Everyone has a university, a department and a reputation.", "/brand-assets/ojax-campus-hero.png"],
  ] as const;

  const content = (() => {
    if (screen === "splash") return <div className="proto-splash" onClick={() => go("onboarding")}><div className="proto-logo-large"><LogoMark size={64} /><b>Oja<span>X</span></b></div><p>Your campus, one market.</p><small>Tap to continue</small></div>;
    if (screen === "onboarding") { const item = onboarding[onboard]; return <div className="proto-onboard"><button className="proto-skip" onClick={() => go("login")}>Skip</button><div className="proto-onboard-art"><img src={item[2]} alt="" /></div><div className="proto-onboard-copy"><div className="proto-dots">{onboarding.map((_, i) => <i className={i === onboard ? "on" : ""} key={i} />)}</div><h1>{item[0]}</h1><p>{item[1]}</p><button className="proto-primary" onClick={() => onboard === onboarding.length - 1 ? go("login") : setOnboard((n) => n + 1)}>{onboard === onboarding.length - 1 ? "Create an account" : "Continue"}<Icon name="arrowR" size={16} /></button><button className="proto-text-btn" onClick={() => go("login")}>I already have an account</button></div></div>; }
    if (screen === "login") return <div className="proto-form-screen"><AppBar title="Welcome back" back onBack={() => go("onboarding")} /><div className="proto-form-intro"><div className="proto-form-mark"><LogoMark size={33} /></div><h1>Welcome back, <em>student.</em></h1><p>Sign in to keep up with your campus.</p></div><label>Email address<input placeholder="you@unilag.edu.ng" /></label><label>Password<div className="proto-input-suffix"><input type="password" placeholder="••••••••" /><Icon name="eyeOff" size={16} /></div></label><button className="proto-primary" onClick={() => go("home")}>Log in <Icon name="arrowR" size={16} /></button><button className="proto-forgot">Forgot password?</button><div className="proto-or"><span />or<span /></div><button className="proto-secondary" onClick={() => go("home")}>Continue with Google</button><p className="proto-bottom-copy">New to OjaX? <button onClick={() => go("onboarding")}>Create account</button></p></div>;
    if (screen === "home") return <div className="proto-screen"><AppBar title="OjaX" action={<div className="proto-app-actions"><button className="proto-icon-btn"><Icon name="bell" size={17} /></button><button className="proto-avatar" onClick={() => go("profile")}>TA</button></div>} /><div className="proto-scroll"><div className="proto-greeting"><div><small>GOOD MORNING, TUNDE</small><h1>Find your next <em>win.</em></h1></div><span className="proto-campus-chip"><Icon name="school" size={13} /> UNILAG</span></div><div className="proto-search" onClick={() => go("browse")}><Icon name="search" size={17} /><span>Search phones, textbooks, fashion…</span><b>⌘ K</b></div><SectionTitle title="Popular categories" action="See all" onAction={() => go("browse")} /><div className="proto-categories">{[["smartphone","Phones","#e9f6ef"],["laptop","Laptops","#edf1ff"],["shirt","Fashion","#fff0e8"],["book","Books","#fff7df"]].map(([ic, t, bg]) => <button key={t} onClick={() => go("browse")}><span style={{background:bg}}><Icon name={ic} size={18} /></span><small>{t}</small></button>)}</div><SectionTitle title="Recommended for you" action="View all" onAction={() => go("browse")} /><div className="proto-product-grid">{products.slice(0, 4).map((p) => <ProductCard key={p[0]} p={p} onClick={() => go("detail")} />)}</div><div className="proto-promo"><span><Icon name="shield" size={22} /></span><div><b>Trade with confidence</b><small>Meet at verified safe spots on campus.</small></div><Icon name="arrowR" size={15} /></div><SectionTitle title="Upcoming on campus" action="See events" onAction={() => go("events")} /><div className="proto-event-mini" onClick={() => go("event")}><img src="/brand-assets/ojax-campus-event.png" alt="" /><div><small>FRI · 15 SEP · 4:00 PM</small><b>Campus Creative Meet-up</b><span><Icon name="location" size={12} /> New Hall · UNILAG</span></div><Icon name="arrowR" size={15} /></div></div><BottomNav screen={screen} go={go} /></div>;
    if (screen === "browse") return <div className="proto-screen"><AppBar title="Browse" back onBack={() => go("home")} action={<div className="proto-app-actions"><button className="proto-icon-btn"><Icon name="heart" size={17} /></button><button className="proto-icon-btn"><Icon name="filter" size={17} /></button></div>} /><div className="proto-scroll"><div className="proto-search active"><Icon name="search" size={17} /><span>Search listings</span><b>×</b></div><div className="proto-filter-row"><button className="active">All items</button><button>Nearby</button><button>Under ₦50k</button><button>Newest</button></div><div className="proto-browse-head"><div><small>UNILAG MARKETPLACE</small><h1>1,248 listings</h1></div><button className="proto-sort"><Icon name="filter" size={14} /> Filters</button></div><div className="proto-product-grid browse-grid">{products.map((p) => <ProductCard key={p[0]} p={p} onClick={() => go("detail")} />)}</div></div><BottomNav screen={screen} go={go} /></div>;
    if (screen === "detail") return <div className="proto-screen"><AppBar title="Product details" back onBack={() => go("browse")} action={<button className={`proto-icon-btn ${liked ? "liked" : ""}`} onClick={() => setLiked(!liked)}><Icon name="heart" size={18} /></button>} /><div className="proto-scroll detail-scroll"><div className="proto-detail-image"><img src={product[2]} alt="" /><span className="proto-detail-badge"><Icon name="check" size={12} /> VERIFIED SELLER</span><div className="proto-image-count">1 / 4</div></div><div className="proto-detail-body"><div className="proto-detail-meta"><span>COMPUTING · UNILAG</span><span>2 HOURS AGO</span></div><h1>{product[0]}</h1><div className="proto-price">{product[1]} <span>Negotiable</span></div><p>Clean, reliable and ready for your next semester. Battery is healthy and the seller is available for a safe campus meetup.</p><div className="proto-seller"><span className="proto-avatar large">CA</span><div><b>Chiamaka A. <Icon name="check" size={13} /></b><small>Computer Science · 300L</small><span><Icon name="star" size={12} /> 4.9 · 18 trades</span></div><Icon name="arrowR" size={15} /></div><div className="proto-safety-note"><Icon name="shield" size={19} /><div><b>Safe meetup recommended</b><small>Library gate, Faculty of Engineering</small></div></div><SectionTitle title="You may also like" action="See all" onAction={() => go("browse")} /><div className="proto-related">{products.slice(1, 3).map((p) => <ProductCard key={p[0]} p={p} onClick={() => go("detail")} />)}</div></div></div><div className="proto-detail-cta"><button className="proto-secondary" onClick={() => go("chat")}><Icon name="chat" size={16} /> Chat seller</button><button className="proto-primary" onClick={() => go("chat")}>Buy now <Icon name="arrowR" size={16} /></button></div></div>;
    if (screen === "sell") { const steps = ["Photos", "Details", "Price", "Pickup", "Preview"]; return <div className="proto-screen"><AppBar title="Sell an item" back onBack={() => go("home")} /><div className="proto-scroll proto-sell"><div className="proto-stepper">{steps.map((s, i) => <span key={s} className={i <= sellStep ? "on" : ""}><i>{i < sellStep ? "✓" : i + 1}</i>{s}</span>)}</div>{sellStep === 0 && <><h1>Show it at its best.</h1><p className="proto-muted">Add up to 8 clear photos. Your first photo becomes the cover.</p><div className="proto-upload-grid"><button className="cover-upload"><Icon name="camera" size={25} /><b>Add photos</b><small>JPG, PNG up to 10MB</small></button>{["airpods-pro-2.jpg","google-pixel-8-pro.jpg","air-force-1.jpg"].map((x) => <img src={`/seed/${x}`} alt="" key={x} />)}</div></>}{sellStep === 1 && <><h1>Tell us about it.</h1><p className="proto-muted">A clear title helps the right buyer find you.</p><label>Item title<input placeholder="e.g. iPhone 13 128GB" /></label><label>Category<select><option>Electronics</option><option>Fashion</option><option>Textbooks</option></select></label><label>Condition<select><option>Like new</option><option>Good</option><option>Fair</option></select></label></>}{sellStep === 2 && <><h1>Name your price.</h1><p className="proto-muted">Be fair. Be clear. You can always negotiate.</p><label>Price (₦)<input placeholder="45000" inputMode="numeric" /></label><div className="proto-toggle-row"><span>Price is negotiable</span><i className="on" /></div></>}{sellStep === 3 && <><h1>Where can you meet?</h1><p className="proto-muted">Choose a familiar, public place on your campus.</p><label>Meetup spot<select><option>UNILAG Main Library</option><option>Faculty of Engineering</option><option>Students' Union Building</option></select></label><div className="proto-safety-note"><Icon name="shield" size={19} /><div><b>Safety first</b><small>We recommend busy places in daylight.</small></div></div></>}{sellStep === 4 && <><h1>Looks good.</h1><p className="proto-muted">Review your listing before it goes live.</p><div className="proto-preview-card"><img src="/seed/airpods-pro-2.jpg" alt="" /><div><small>VERIFIED SELLER · UNILAG</small><b>AirPods Pro (2nd Gen)</b><strong>₦185,000</strong><span>Library gate · Negotiable</span></div></div><div className="proto-publish"><Icon name="check" size={17} /> Ready to publish</div></>}</div><div className="proto-detail-cta"><button className="proto-secondary" onClick={() => sellStep === 0 ? go("home") : setSellStep((n) => n - 1)}>Back</button><button className="proto-primary" onClick={() => sellStep === steps.length - 1 ? go("home") : setSellStep((n) => n + 1)}>{sellStep === steps.length - 1 ? "Publish listing" : "Continue"}<Icon name="arrowR" size={16} /></button></div></div>; }
    if (screen === "events") return <div className="proto-screen"><AppBar title="Events" action={<button className="proto-icon-btn"><Icon name="search" size={17} /></button>} /><div className="proto-scroll"><div className="proto-event-hero"><img src="/brand-assets/ojax-campus-event.png" alt="" /><div><small>FEATURED THIS WEEK</small><h1>Find your people.</h1><p>Campus culture, in one place.</p></div></div><div className="proto-filter-row"><button className="active">For you</button><button>Today</button><button>This week</button></div><SectionTitle title="Trending events" action="See all" /><div className="proto-event-list">{["Campus Creative Meet-up","NACOSS Tech Hangout","Sunday Service & Chill"].map((x, i) => <button className="proto-event-row" key={x} onClick={() => go("event")}><img src={`/seed/${["college-textbooks.jpg","jbl-flip-4.jpg","kanken-backpack.jpg"][i]}`} alt="" /><div><small>{i + 15} SEP · {i + 4}:00 PM</small><b>{x}</b><span><Icon name="location" size={12} /> UNILAG · {24 + i * 18} going</span></div><Icon name="arrowR" size={15} /></button>)}</div></div><BottomNav screen={screen} go={go} /></div>;
    if (screen === "event") return <div className="proto-screen"><AppBar title="Event details" back onBack={() => go("events")} /><div className="proto-scroll"><div className="proto-event-detail-cover"><img src="/brand-assets/ojax-campus-event.png" alt="" /></div><div className="proto-event-body"><small className="proto-orange-label">FRIDAY · 15 SEP · 4:00 PM</small><h1>Campus Creative Meet-up</h1><p>Bring your work, your ideas and your people. A relaxed evening for students building interesting things.</p><div className="proto-event-info"><span><Icon name="location" size={17} /><b>New Hall, UNILAG<small>University of Lagos</small></b></span><span><Icon name="user" size={17} /><b>24 going<small>Hosted by OjaX Creatives</small></b></span></div><button className="proto-primary full" onClick={() => go("events")}>RSVP — Free <Icon name="arrowR" size={16} /></button><SectionTitle title="About the organizer" /><div className="proto-organizer"><span className="proto-avatar">OC</span><div><b>OjaX Creatives</b><small>Student organisation · Verified</small></div><Icon name="arrowR" size={15} /></div></div></div></div>;
    if (screen === "chat") return <div className="proto-screen"><AppBar title="Messages" action={<button className="proto-icon-btn"><Icon name="edit" size={17} /></button>} /><div className="proto-scroll"><div className="proto-search"><Icon name="search" size={17} /><span>Search conversations</span></div><div className="proto-chat-context"><img src="/seed/dell-xps-13.jpg" alt="" /><div><small>ABOUT THIS ITEM</small><b>MacBook Pro 2019</b><span>₦620,000 · Chiamaka A.</span></div><Icon name="arrowR" size={15} /></div><div className="proto-message-list">{people.map((p, i) => <button key={p} className="proto-message-row"><span className={`proto-avatar p${i}`}>{p.split(" ").map((x) => x[0]).join("")}</span><div><b>{p}{i < 2 && <i />}</b><small>{["Is the price negotiable?", "See you at the library gate.", "Thanks for the quick response!", "Are you going for the event?"][i]}</small></div><time>{i + 1}h</time></button>)}</div></div><BottomNav screen={screen} go={go} /></div>;
    if (screen === "profile") return <div className="proto-screen"><AppBar title="Profile" action={<button className="proto-icon-btn"><Icon name="edit" size={17} /></button>} /><div className="proto-scroll"><div className="proto-profile-head"><span className="proto-profile-photo">TA</span><h1>Tunde A.</h1><p>Computer Engineering · 400L</p><span className="chip chip-green"><Icon name="check" size={12} /> VERIFIED STUDENT</span></div><div className="proto-profile-stats"><span><b>4.8</b><small>Trust score</small></span><span><b>12</b><small>Trades</small></span><span><b>8</b><small>Events joined</small></span></div><div className="proto-menu-list">{[["dashboard","My dashboard"],["heart","Saved items"],["shield","Safety hub"],["bell","Notifications"],["settings","Settings"]].map(([ic, label]) => <button key={label} onClick={() => go(label === "Safety hub" ? "safety" : label === "Saved items" ? "saved" : label === "Notifications" ? "notifications" : "dashboard")}><span><Icon name={ic} size={17} /></span><b>{label}</b><Icon name="arrowR" size={14} /></button>)}</div></div><BottomNav screen={screen} go={go} /></div>;
    if (screen === "safety" || screen === "notifications" || screen === "saved" || screen === "dashboard") { const map: Record<string, [string, string, string]> = { safety: ["Safety hub", "Trade with confidence, wherever you are.", "shield"], notifications: ["Notifications", "Stay close to what matters.", "bell"], saved: ["Saved items", "Your little shortlist of good finds.", "heart"], dashboard: ["My dashboard", "Your campus activity at a glance.", "dashboard"] }; const [title, sub, ic] = map[screen]; return <div className="proto-screen"><AppBar title={title} back onBack={() => go("profile")} /><div className="proto-scroll"><div className="proto-page-hero"><span><Icon name={ic} size={23} /></span><h1>{title}</h1><p>{sub}</p></div>{screen === "safety" && <div className="proto-list-cards">{[["Meet in verified spots","Busy, familiar places are always better."],["Keep chats on OjaX","Your conversations are your protection."],["Never pay before you inspect","If it feels rushed, walk away."]].map(([x,y]) => <div className="proto-list-card" key={x}><span><Icon name="check" size={16} /></span><div><b>{x}</b><small>{y}</small></div><Icon name="arrowR" size={14} /></div>)}</div>}{screen === "saved" && <div className="proto-product-grid">{products.slice(0, 4).map((p) => <ProductCard key={p[0]} p={p} onClick={() => go("detail")} />)}</div>}{screen === "dashboard" && <div className="proto-dashboard"><div><small>THIS MONTH</small><b>₦246,500</b><span>total sales value</span></div><div><small>TRUST SCORE</small><b>4.8 ★</b><span>12 completed trades</span></div><SectionTitle title="Recent activity" />{people.slice(0, 3).map((p) => <div className="proto-activity" key={p}><span className="proto-avatar">{p[0]}</span><span><b>{p} viewed your listing</b><small>MacBook Pro 2019 · 2h ago</small></span></div>)}</div>}{screen === "notifications" && <div className="proto-notification-list">{["Chiamaka replied to your message","Your listing was saved","Campus Creative Meet-up is tomorrow","Your student verification is complete"].map((x, i) => <div className="proto-notification" key={x}><span><Icon name={i === 3 ? "shield" : i === 2 ? "calendar" : "bell"} size={16} /></span><div><b>{x}</b><small>{i + 1} hour{i ? "s" : ""} ago</small></div></div>)}</div>}</div></div>; }
    if (screen === "empty") return <div className="proto-screen"><AppBar title="Saved items" back onBack={() => go("profile")} /><div className="proto-empty"><div><Icon name="heart" size={34} /></div><h1>Nothing saved yet.</h1><p>When something catches your eye, tap the heart and it will live here.</p><button className="proto-primary" onClick={() => go("browse")}>Explore the market</button></div></div>;
    return <div className="proto-screen"><AppBar title="Loading" /><div className="proto-loading"><div className="proto-skeleton wide" /><div className="proto-skeleton title" /><div className="proto-skeleton line" /><div className="proto-skeleton grid" /></div></div>;
  })();
  return <div className="prototype-page"><div className="prototype-topbar"><Link to="/">← Back to OjaX web</Link><span>Interactive mobile product prototype</span><button onClick={() => go("splash")}>Replay flow</button></div><div className="prototype-stage"><div className="prototype-device"><div className="proto-status"><span>9:41</span><span>● ◔ ▰</span></div>{content}</div><div className="prototype-rail"><small>SCREEN MAP</small><b>OjaX mobile flows</b>{([["home","Home"],["browse","Marketplace browse"],["detail","Product detail"],["sell","Sell item flow"],["events","Events discovery"],["event","Event details"],["chat","Chat experience"],["profile","Verified profile"],["safety","Safety hub"],["notifications","Notifications"],["saved","Saved items"],["dashboard","User dashboard"],["empty","Empty state"],["loading","Loading state"]] as [Screen,string][]).map(([s, label]) => <button className={screen === s ? "on" : ""} key={s} onClick={() => go(s)}><i />{label}</button>)}</div></div></div>;
}
